### ISSUE TITLE
Fraud assessment "undefined"

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-evaluate#64]
When we evaluate measurements, the fraud assessment pipeline often assigns an `undefined` value to some.

**Comment by bajtos** [comment]
Data for round 528:

```
dry-run
  measurements_OK: 187,880
  measurements_INVALID_TASK: 9,446
  measurements_DUP_INET_GROUP: 165,958
total: 363,284

production:
  measurements_OK: 182,212
  measurements_INVALID_TASK: 9,446
  measurements_DUP_INET_GROUP: 153,823
total: 345,482
```
